name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  dotnet:
    name: .NET
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore rn-fabricator.sln

      - name: Build
        run: dotnet build rn-fabricator.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test rn-fabricator.sln --no-build --configuration Release
